### ISSUE TITLE
Why do we check if p = 2p + 1 is prime after finding already prime p?

### ISSUE THREAD

**Issue by fylmr** [RyanRiddle/elgamal#12]
https://github.com/RyanRiddle/elgamal/blob/19ef936d748f8d90800c296f9813cb00dbd60b95/elgamal.py#L204-L206

Hi! I was wondering if it is really necessary, and couldn't find any clue in my books. Why do we do this?

**Comment by RyanRiddle** [comment]
Sure, so we want the final p to be prime.  If we have a prime p there's no guarantee that 2*p + 1 will be prime.  For example, p = 7: 2*p + 1 = 15 which is composite.
