### ISSUE TITLE
Running test() returns False

### ISSUE THREAD

**Issue by EmadY** [RyanRiddle/elgamal#2]
Running test() actually returns False. (After I comment out the french and the Chinese as well).

**Comment by RyanRiddle** [comment]
Does it fail consistently for you? I just ran it and it passed.

**Comment by RyanRiddle** [comment]
Did you change the confidence level when you called generate_keys() or find_prime()?  If you generate keys with a low confidence level then it is more likely that you will create keys using numbers that are not prime.  If the keys are not generated using prime numbers encrypt() and decrypt() will not work properly and will cause test() to return False.  If you did not change the confidence level it is very unlikely but still possible that you got bad keys.
